### ISSUE TITLE
Missing Western & Wales

### ISSUE THREAD

**Issue by jimbok8** [anisotropi4/nesa#2]
Thanks very much for this very useful tool and data.
I notice that Western & Wales folder/data  seems to be missing - is it possible you could run this on the 2021 files please?
Thanks
Jim

**Comment by anisotropi4** [comment]
Hi Jim,

Thanks. There are two things here, one is that it looks like "Western & Wales" were amalgamated into "Western" and/or "London North Western (South)" and I didn't spot this. Then, clearly in celebration of dydd dewi Sant, the new March 2022 NESA publication came out this so I don't know if I can publish the 2021 files as I don't have a copy and they aren't there any more.
![Current Network Rail NESA download page](https://user-images.githubusercontent.com/27144121/156876384-3d0aedad-9ed1-4526-b828-4affe0de90ee.png)

Given this, I will run the scripts and get a March 2022 cut published this week, and check that none of Wales is missing this time. 

Does that help?

Will

**Comment by anisotropi4** [comment]
I'm going to close this as I have now uploaded the processed *Western* route data. It was there but I hadn't added the 'Western' sub-folders and updated the README.md.  I

 have also added a note as gauging tables for Wales are now split between 'Western' for South/Mid Wales and London North Western (North) for North Wales. Either way, as there is a new NESA publication I'll be update this at some point the week. It's GitHub so you can get the previous branch with this 2021 data or the latest cut in a few days time.

Hopefully that addresses the issue of the missing South/Mid Wales data.

**Comment by jimbok8** [comment]
Thanks very much.
Jim
